export const DoctorNames = [
  { id: 1, name: "Dr. Aisha Khan" },
  { id: 2, name: "Dr. Rohan Mehta" },
  { id: 3, name: "Dr. Priya Sharma" },
  { id: 4, name: "Dr. Vikram Patel" },
  { id: 5, name: "Dr. Neha Desai" },
  { id: 6, name: "Dr. Arjun Nair" },
  { id: 7, name: "Dr. Sneha Roy" },
  { id: 8, name: "Dr. Manish Gupta" },
  { id: 9, name: "Dr. Kavita Reddy" },
  { id: 10, name: "Dr. Aditya Verma" },
  { id: 11, name: "Dr. Pooja Singh" },
  { id: 12, name: "Dr. Siddharth Rao" },
  { id: 13, name: "Dr. Anjali Menon" },
  { id: 14, name: "Dr. Harsh Vora" },
  { id: 15, name: "Dr. Tanvi Joshi" },
  { id: 16, name: "Dr. Deepak Bansal" },
  { id: 17, name: "Dr. Isha Malhotra" },
  { id: 18, name: "Dr. Karan Bhatt" },
  { id: 19, name: "Dr. Ritu Sinha" },
  { id: 20, name: "Dr. Nikhil Saxena" },
];

export const patientItems = [
  { id: 1, name: "Aarav Sharma" },
  { id: 2, name: "Saanvi Patel" },
  { id: 3, name: "Vivaan Reddy" },
  { id: 4, name: "Anaya Mehra" },
  { id: 5, name: "Ishaan Nair" },
  { id: 6, name: "Diya Verma" },
  { id: 7, name: "Reyansh Gupta" },
  { id: 8, name: "Kiara Joshi" },
  { id: 9, name: "Atharv Malhotra" },
  { id: 10, name: "Myra Singh" },
  { id: 11, name: "Ayaan Sinha" },
  { id: 12, name: "Sara Kapoor" },
  { id: 13, name: "Kabir Bansal" },
  { id: 14, name: "Aadhya Desai" },
  { id: 15, name: "Krish Bhatt" },
  { id: 16, name: "Meher Jain" },
  { id: 17, name: "Arnav Vora" },
  { id: 18, name: "Riya Menon" },
  { id: 19, name: "Dhruv Saxena" },
  { id: 20, name: "Tara Roy" },
];

